language: node_js
node_js:
  - "node"
  - "8"
  - "6"

services:
  - mongodb

env:
  - NODE_ENV=travis

before_script:
  - sleep 5
  - mongo demo --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

cache: yarn
