language: node_js
node_js:
  - "node"
  - "8"
  - "6"

services:
  - mongodb

env:
  - NODE_ENV=test

before_script:
  - sleep 5
  - mongo demo --eval 'db.createUser({user:"root",pwd:"toortoor",roles:["readWrite"]});'

cache: yarn
